### ISSUE TITLE
Can't assign to Payload because it's read-only?

### ISSUE THREAD

**Issue by winzig** [qdrant/qdrant-dotnet#39]
Just starting to experiment with Qdrant, running into something weird. 

In my demo, I'm trying to take a dynamic payload in my method params:

```csharp
public void InsertPayload(float[] vectors, Google.Protobuf.Collections.MapField<string, Value> payload)
{
    ... 

    var point = new PointStruct
    {
        Vectors = vectors,
        Payload = payload
    };

    ...
}
```

This won't compile, `Payload` shows this error: 

> Property or indexer 'PointStruct.Payload' cannot be assigned to -- it is read only

The only way I seem to be able to set the payload when creating a `PointStruct` is to either do so explicitly, hard-coded:

```csharp
var point = new PointStruct
{
    Vectors = vectors,
    Payload = 
    {
        { "TestKey", "TestValue" }
    }
};
```

or by adding string/value pairs manually:

```csharp
var point = new PointStruct
{
    Vectors = vectors
};

point.Payload.Add("TestKey", "TestValue");
```

I assume I'm just using the library wrong or misunderstanding how this all works?

**Comment by ranjancse26** [comment]
You could also do like this

` point.Payload.Add(payload);`

**Comment by winzig** [comment]
@ranjancse26 Thank you, that works!
