### ISSUE TITLE
Add HTTP API support

### ISSUE THREAD

**Issue by TonySkorik** [qdrant/qdrant-dotnet#43]
While integrating Qdrant in our workflows I've built the Qdrant's HTTP API client.
For the sake of completeness I think it would be great to add an HTTP implementation to this client as well.

My Qdrant HTTP client repo is located here -> https://github.com/aliexpressru/qdrant-client

I will be happy to connect and contribute parts that you find interesting (if any 😊).

**Comment by Anush008** [comment]
Hey @TonySkorik. Thanks for raising the issue.
Currently, there are no plans to support REST for the Rust, Java, C# and Go clients.
