### ISSUE TITLE
Implement trace provider

### ISSUE THREAD

**Issue by timheuer** [qdrant/qdrant-dotnet#49]
For cloud native observability, it would be nice to have a tracing story that we could leverage to add to OpenTelemetry.

**Comment by russcam** [comment]
Hi @timheuer, the gRPC client should [produce tracing spans from `Grpc.Net.Client` diagnostic source](https://learn.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-8.0#grpc-client-tracing), similiar to other gRPC clients. Is that sufficient for what you're looking for?
