### ISSUE TITLE
Grpc.Core.RpcException : Status(StatusCode="Unimplemented", Detail="") in Qdrant.Client.CollectionTests.CollectionExists

### ISSUE THREAD

**Issue by gpww** [qdrant/qdrant-dotnet#50]
the funtion qdrantClient.CollectionExistsAsync("collection_1") has not been implemented?

![1712809602219](https://github.com/qdrant/qdrant-dotnet/assets/11976499/fcc84f9f-d40c-479f-837e-b3465620ad92)

**Comment by russcam** [comment]
Hi @gpww, 

the collection exists API was added in qdrant release [v1.8.0](https://github.com/qdrant/qdrant/releases/tag/v1.8.0). Are you running against at least v1.8.0?

**Comment by gpww** [comment]
> Hi @gpww,
> 
> the collection exists API was added in qdrant release [v1.8.0](https://github.com/qdrant/qdrant/releases/tag/v1.8.0). Are you running against at least v1.8.0?

yes, as the following screen shot:
![1713282272061](https://github.com/qdrant/qdrant-dotnet/assets/11976499/9edfbed1-7734-4f6d-a65f-d17ea3d7bca5)

I implemented a simple version. It just works for me now.
`public async Task<bool> CollectionExistsAsync(string collectionName, CancellationToken cancellationToken = default)
    {
        var collections = await GetCollectionListAsync(cancellationToken);
        return collections.Contains(collectionName);
    }`

**Comment by Anush008** [comment]
@gpww, the screenshot seems to be of the client library version. Can you confirm the version of your Qdrant image? Should 1.8.0 or above.

**Comment by matengo** [comment]
Same with 1.9

**Comment by russcam** [comment]
**The version of [qdrant must be at least v1.8.0](https://github.com/qdrant/qdrant/releases/tag/v1.8.0), as this is the version in which the collection exists API was added.** Then, you should consider using a **version of the .NET qdrant client** that is _at least_ the same major and minor version as the version of qdrant.
