### ISSUE TITLE
Getting error 'Invalid URI: The hostname could not be parsed.'

### ISSUE THREAD

**Issue by acrigney** [qdrant/qdrant-dotnet#51]
New user question
I am getting this error when I try and connect to my qDrant cloud cluster in C#
Here is my code

'Invalid URI: The hostname could not be parsed.'

public QdrantClient GetClient()
{            
    var client = new QdrantClient(
      host: "https://GUID.us-east4-0.gcp.cloud.qdrant.io:6333",
      https: true,
      apiKey: "???"
    );
    return( client );
}

I took the sensitive info out

Best Regards,
                         Alistair

**Comment by Anush008** [comment]
The host should be `guid.us-east4-0.gcp.cloud.qdrant.io`.
