### ISSUE TITLE
do the fucking homeworks: Documentation

### ISSUE THREAD

**Issue by Porkechebure** [qdrant/qdrant-dotnet#59]
Write some decent documentation with code examples and don't leave people to guess your half baked work.

Example:
![image](https://github.com/user-attachments/assets/8a9a6398-057b-4aa0-8424-9e7a6c223394)

Does not fucking work.
And if you try using it with SearchAsync it's even worse and throws more errors.
Provide working examples of how to use this.

**Comment by timvisee** [comment]
Closing this due to swearing and hate speech.

Please feel free to open a new issue on this with a more acceptable tone of voice. Then we're more than happy to help you.
