### ISSUE TITLE
Documentation prettypleasekuwaiiikisssss

### ISSUE THREAD

**Issue by Porkechebure** [qdrant/qdrant-dotnet#63]
https://github.com/qdrant/qdrant-dotnet/issues/59#event-13603197818
Since you cry here, then here's one sugar coated:

Please do the documentation and not these 3 scrawny examples currently provided which serve no purpose

**Comment by Anush008** [comment]
Hey.
You can refer to https://qdrant.tech/documentation/concepts.
All sections have code snippets in multiple languages including C#.

**Comment by Anush008** [comment]
Added a note in the README too.
https://github.com/qdrant/qdrant-dotnet#-documentation
