### ISSUE TITLE
Add Healthcheks endpoints to client

### ISSUE THREAD

**Issue by Alirexaa** [qdrant/qdrant-dotnet#70]
Qdrant has three endpoint for checking server health status.

for more information see : https://qdrant.tech/documentation/guides/monitoring/#kubernetes-health-endpoints

We should have APIs for these endpoints in the client

API Proposal:

```diff
+ public Task<HealthResult> HealthAsync(TimeSpan? timeout = null,CancellationToken cancellationToken = default);

+ public Task<LiveResult> LiveAsync(TimeSpan? timeout = null,CancellationToken cancellationToken = default);

+ public Task<ReadyResult> ReadyAsync(TimeSpan? timeout = null,CancellationToken cancellationToken = default);
```

**Comment by Anush008** [comment]
`/livez` and `/readyz` are not needed in the clients.
