### ISSUE TITLE
How to download and restore snapshots?

### ISSUE THREAD

**Issue by lilhoser** [qdrant/qdrant-dotnet#75]
Seems like the topic is covered [here](https://qdrant.tech/documentation/tutorials/create-snapshot/) for python and there are some API's in .NET/C# for creating and enumerating snapshots, but how are they downloaded locally and restored?

**Comment by russcam** [comment]
Hi @lilhoser, the client is generated from the qdrant protos, and the [snapshot gRPC service](https://github.com/qdrant/qdrant/blob/5b578c4f34188f0474f901e49d4726213596433d/lib/api/src/grpc/proto/snapshots_service.proto#L8-L33) doesn't expose download/upload snapshot methods. I'll see if there are plans to expose them.

We could consider patching in methods that call the REST APIs as an alternative.

**Comment by timvisee** [comment]
> I'll see if there are plans to expose them.

We did not implement them because sending big files over gRPC is quite cumbersome and error prone.

> We could consider patching in methods that call the REST APIs as an alternative.

If that would be possible (without too much effort), it would probably be the best option for now. Of course, the catch here is that HTTP uses a different port.

**Comment by russcam** [comment]
@lilhoser you may want to stream the snapshot to file, to avoid buffering all data in memory 

```c#
public async Task DownloadSnapshotAsync(
    Uri baseAddress, 
    string collectionName, 
    string snapshotName, 
    string outputPath)
{
    using var httpClient = new HttpClient();
    httpClient.BaseAddress = baseAddress;    
    var snapshotUri = $"collections/{collectionName}/snapshots/{snapshotName}";  
    using var response = await httpClient.GetAsync(snapshotUri, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
    response.EnsureSuccessStatusCode();
    var target = Path.Combine(outputPath, snapshotName);
    using var downloadStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
    using var fileStream = new FileStream(target, FileMode.Create, FileAccess.Write, FileShare.None, bufferSize: 4096, useAsync: true);
    await downloadStream.CopyToAsync(fileStream).ConfigureAwait(false);
}
```

**Comment by lilhoser** [comment]
Great suggestion, thank you for the code!
